import { prisma } from "@/lib/db/prisma"
import { AIAnalysisService } from "@/lib/ai/analysis-service"
import { enqueueJob } from "./scheduler"
import type { JobData, JobResult, JobHandler } from "./scheduler"
import type { AnalysisInput } from "@/types"

export class AnalyzeChangeJob implements JobHandler {
  async execute(job: JobData): Promise<JobResult> {
    const changeId = job.targetId
    if (!changeId) {
      return { success: false, error: "targetId (changeId) requis" }
    }

    // Récupérer le changement avec toutes ses données
    const change = await prisma.change.findFirst({
      where: { id: changeId, orgId: job.orgId },
      include: {
        tickets: true,
        commits: true,
        pullRequests: true,
        sourceFiles: true,
      },
    })

    if (!change) {
      return { success: false, error: "Changement introuvable" }
    }

    // Construire l'input d'analyse à partir des données disponibles
    const input: AnalysisInput = {}

    if (change.tickets.length > 0) {
      const ticket = change.tickets[0]
      input.jiraTicket = [
        `Ticket: ${ticket.externalId}`,
        `Titre: ${ticket.title}`,
        `Type: ${ticket.type || "N/A"}`,
        `Priorité: ${ticket.priority || "N/A"}`,
        ticket.description ? `Description: ${ticket.description}` : "",
      ].filter(Boolean).join("\n")
    }

    if (change.description) {
      input.functionalDescription = change.description
    }

    if (change.pullRequests.length > 0) {
      const pr = change.pullRequests[0]
      input.pullRequest = [
        `PR: ${pr.externalId}`,
        `Titre: ${pr.title}`,
        `Branche: ${pr.sourceBranch || "?"} → ${pr.targetBranch || "?"}`,
        pr.description ? `Description: ${pr.description}` : "",
      ].filter(Boolean).join("\n")
    }

    if (change.commits.length > 0) {
      const diffs: string[] = []
      for (const commit of change.commits) {
        if (commit.diff) diffs.push(commit.diff)
      }
      if (diffs.length > 0) {
        input.gitDiff = diffs.join("\n\n")
      } else {
        input.gitDiff = change.commits.map((c) => `${c.sha.slice(0, 7)}: ${c.message}`).join("\n")
      }
    }

    // Lancer l'analyse
    const result = await AIAnalysisService.analyze(input, job.orgId)

    if (result.success && result.analysisId) {
      // Lier l'analyse au changement
      await prisma.aIAnalysis.update({
        where: { id: result.analysisId },
        data: { changeId },
      })

      // Enchaîner automatiquement : générer les documents
      if (result.result) {
        const docTypes = result.result.documentsToUpdate || []

        // Générer au moins une spec technique et une release note
        const typesToGenerate = new Set<string>()
        if (docTypes.some((d: string) => d.toLowerCase().includes("technique") || d.toLowerCase().includes("spec"))) {
          typesToGenerate.add("TECHNICAL_SPEC")
        }
        if (docTypes.some((d: string) => d.toLowerCase().includes("release") || d.toLowerCase().includes("note"))) {
          typesToGenerate.add("RELEASE_NOTE")
        }
        // Toujours générer une fiche d'impact si risque élevé
        const highRisks = [
          result.result.functionalRisk,
          result.result.technicalRisk,
          result.result.securityRisk,
        ].some((r) => r.level === "high" || r.level === "critical")
        if (highRisks) {
          typesToGenerate.add("IMPACT_SHEET")
        }

        for (const docType of typesToGenerate) {
          await enqueueJob({
            type: "GENERATE_DOCUMENT",
            orgId: job.orgId,
            targetId: result.analysisId,
            payload: {
              documentType: docType,
              changeId,
              projectId: change.projectId,
            },
            priority: 3,
          })
        }
      }

      // Notifier les validateurs
      await enqueueJob({
        type: "SEND_NOTIFICATION",
        orgId: job.orgId,
        targetId: changeId,
        payload: {
          notificationType: "analysis_ready",
          changeTitle: change.title,
          analysisId: result.analysisId,
          confidence: result.result?.confidenceLevel,
        },
        priority: 2,
      })
    }

    return {
      success: result.success,
      data: {
        analysisId: result.analysisId,
        tokensUsed: result.tokensUsed,
        confidence: result.result?.confidenceLevel,
        autoGeneratedDocs: result.result?.documentsToUpdate?.length || 0,
      },
      error: result.error,
    }
  }
}
